spring:
  datasource:
    username: dev
    password: 111111
    url: jdbc:mysql://localhost:3306/Seaport?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

qiniu:
  accessKey: k1k_lcCFc9PzpRSnECppmJbl_KDr5rgmXcBncmXn
  secretKey: bA3ZI0LkcE54FeMSmlw2K2OPrltVv4UYm00Ftyfl

logging:
  path: /data/log